node shex-partition.js fhir-shapes.shex '<Address>' > ./fhir-shapes-separated/Address.shex
node shex-partition.js fhir-shapes.shex '<AllergyIntolerance>' > ./fhir-shapes-separated/AllergyIntolerance.shex
node shex-partition.js fhir-shapes.shex '<AllergyIntolerance.event>' > ./fhir-shapes-separated/AllergyIntolerance.event.shex
node shex-partition.js fhir-shapes.shex '<Appointment>' > ./fhir-shapes-separated/Appointment.shex
node shex-partition.js fhir-shapes.shex '<Appointment.participant>' > ./fhir-shapes-separated/Appointment.participant.shex
node shex-partition.js fhir-shapes.shex '<AppointmentResponse>' > ./fhir-shapes-separated/AppointmentResponse.shex
node shex-partition.js fhir-shapes.shex '<Attachment>' > ./fhir-shapes-separated/Attachment.shex
node shex-partition.js fhir-shapes.shex '<AuditEvent>' > ./fhir-shapes-separated/AuditEvent.shex
node shex-partition.js fhir-shapes.shex '<AuditEvent.event>' > ./fhir-shapes-separated/AuditEvent.event.shex
node shex-partition.js fhir-shapes.shex '<AuditEvent.object>' > ./fhir-shapes-separated/AuditEvent.object.shex
node shex-partition.js fhir-shapes.shex '<AuditEvent.object.detail>' > ./fhir-shapes-separated/AuditEvent.object.detail.shex
node shex-partition.js fhir-shapes.shex '<AuditEvent.participant>' > ./fhir-shapes-separated/AuditEvent.participant.shex
node shex-partition.js fhir-shapes.shex '<AuditEvent.participant.network>' > ./fhir-shapes-separated/AuditEvent.participant.network.shex
node shex-partition.js fhir-shapes.shex '<AuditEvent.source>' > ./fhir-shapes-separated/AuditEvent.source.shex
node shex-partition.js fhir-shapes.shex '<BackboneElement>' > ./fhir-shapes-separated/BackboneElement.shex
node shex-partition.js fhir-shapes.shex '<base64Binary>' > ./fhir-shapes-separated/base64Binary.shex
node shex-partition.js fhir-shapes.shex '<Basic>' > ./fhir-shapes-separated/Basic.shex
node shex-partition.js fhir-shapes.shex '<Binary>' > ./fhir-shapes-separated/Binary.shex
node shex-partition.js fhir-shapes.shex '<BodySite>' > ./fhir-shapes-separated/BodySite.shex
node shex-partition.js fhir-shapes.shex '<boolean>' > ./fhir-shapes-separated/boolean.shex
node shex-partition.js fhir-shapes.shex '<Bundle>' > ./fhir-shapes-separated/Bundle.shex
node shex-partition.js fhir-shapes.shex '<Bundle.entry>' > ./fhir-shapes-separated/Bundle.entry.shex
node shex-partition.js fhir-shapes.shex '<Bundle.entry.search>' > ./fhir-shapes-separated/Bundle.entry.search.shex
node shex-partition.js fhir-shapes.shex '<Bundle.entry.transaction>' > ./fhir-shapes-separated/Bundle.entry.transaction.shex
node shex-partition.js fhir-shapes.shex '<Bundle.entry.transactionResponse>' > ./fhir-shapes-separated/Bundle.entry.transactionResponse.shex
node shex-partition.js fhir-shapes.shex '<Bundle.link>' > ./fhir-shapes-separated/Bundle.link.shex
node shex-partition.js fhir-shapes.shex '<CarePlan>' > ./fhir-shapes-separated/CarePlan.shex
node shex-partition.js fhir-shapes.shex '<CarePlan.activity>' > ./fhir-shapes-separated/CarePlan.activity.shex
node shex-partition.js fhir-shapes.shex '<CarePlan.activity.detail>' > ./fhir-shapes-separated/CarePlan.activity.detail.shex
node shex-partition.js fhir-shapes.shex '<CarePlan.participant>' > ./fhir-shapes-separated/CarePlan.participant.shex
node shex-partition.js fhir-shapes.shex '<Claim>' > ./fhir-shapes-separated/Claim.shex
node shex-partition.js fhir-shapes.shex '<Claim.coverage>' > ./fhir-shapes-separated/Claim.coverage.shex
node shex-partition.js fhir-shapes.shex '<Claim.diagnosis>' > ./fhir-shapes-separated/Claim.diagnosis.shex
node shex-partition.js fhir-shapes.shex '<Claim.item>' > ./fhir-shapes-separated/Claim.item.shex
node shex-partition.js fhir-shapes.shex '<Claim.item.detail>' > ./fhir-shapes-separated/Claim.item.detail.shex
node shex-partition.js fhir-shapes.shex '<Claim.item.detail.subDetail>' > ./fhir-shapes-separated/Claim.item.detail.subDetail.shex
node shex-partition.js fhir-shapes.shex '<Claim.item.prosthesis>' > ./fhir-shapes-separated/Claim.item.prosthesis.shex
node shex-partition.js fhir-shapes.shex '<Claim.missingTeeth>' > ./fhir-shapes-separated/Claim.missingTeeth.shex
node shex-partition.js fhir-shapes.shex '<Claim.payee>' > ./fhir-shapes-separated/Claim.payee.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse>' > ./fhir-shapes-separated/ClaimResponse.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse.addItem>' > ./fhir-shapes-separated/ClaimResponse.addItem.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse.addItem.adjudication>' > ./fhir-shapes-separated/ClaimResponse.addItem.adjudication.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse.addItem.detail>' > ./fhir-shapes-separated/ClaimResponse.addItem.detail.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse.addItem.detail.adjudication>' > ./fhir-shapes-separated/ClaimResponse.addItem.detail.adjudication.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse.coverage>' > ./fhir-shapes-separated/ClaimResponse.coverage.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse.error>' > ./fhir-shapes-separated/ClaimResponse.error.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse.item>' > ./fhir-shapes-separated/ClaimResponse.item.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse.item.adjudication>' > ./fhir-shapes-separated/ClaimResponse.item.adjudication.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse.item.detail>' > ./fhir-shapes-separated/ClaimResponse.item.detail.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse.item.detail.adjudication>' > ./fhir-shapes-separated/ClaimResponse.item.detail.adjudication.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse.item.detail.subDetail>' > ./fhir-shapes-separated/ClaimResponse.item.detail.subDetail.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse.item.detail.subDetail.adjudication>' > ./fhir-shapes-separated/ClaimResponse.item.detail.subDetail.adjudication.shex
node shex-partition.js fhir-shapes.shex '<ClaimResponse.note>' > ./fhir-shapes-separated/ClaimResponse.note.shex
node shex-partition.js fhir-shapes.shex '<ClinicalImpression>' > ./fhir-shapes-separated/ClinicalImpression.shex
node shex-partition.js fhir-shapes.shex '<ClinicalImpression.finding>' > ./fhir-shapes-separated/ClinicalImpression.finding.shex
node shex-partition.js fhir-shapes.shex '<ClinicalImpression.investigations>' > ./fhir-shapes-separated/ClinicalImpression.investigations.shex
node shex-partition.js fhir-shapes.shex '<ClinicalImpression.ruledOut>' > ./fhir-shapes-separated/ClinicalImpression.ruledOut.shex
node shex-partition.js fhir-shapes.shex '<code>' > ./fhir-shapes-separated/code.shex
node shex-partition.js fhir-shapes.shex '<CodeableConcept>' > ./fhir-shapes-separated/CodeableConcept.shex
node shex-partition.js fhir-shapes.shex '<Coding>' > ./fhir-shapes-separated/Coding.shex
node shex-partition.js fhir-shapes.shex '<Communication>' > ./fhir-shapes-separated/Communication.shex
node shex-partition.js fhir-shapes.shex '<Communication.payload>' > ./fhir-shapes-separated/Communication.payload.shex
node shex-partition.js fhir-shapes.shex '<CommunicationRequest>' > ./fhir-shapes-separated/CommunicationRequest.shex
node shex-partition.js fhir-shapes.shex '<CommunicationRequest.payload>' > ./fhir-shapes-separated/CommunicationRequest.payload.shex
node shex-partition.js fhir-shapes.shex '<Composition>' > ./fhir-shapes-separated/Composition.shex
node shex-partition.js fhir-shapes.shex '<Composition.attester>' > ./fhir-shapes-separated/Composition.attester.shex
node shex-partition.js fhir-shapes.shex '<Composition.event>' > ./fhir-shapes-separated/Composition.event.shex
node shex-partition.js fhir-shapes.shex '<Composition.section>' > ./fhir-shapes-separated/Composition.section.shex
node shex-partition.js fhir-shapes.shex '<ConceptMap>' > ./fhir-shapes-separated/ConceptMap.shex
node shex-partition.js fhir-shapes.shex '<ConceptMap.contact>' > ./fhir-shapes-separated/ConceptMap.contact.shex
node shex-partition.js fhir-shapes.shex '<ConceptMap.element>' > ./fhir-shapes-separated/ConceptMap.element.shex
node shex-partition.js fhir-shapes.shex '<ConceptMap.element.dependsOn>' > ./fhir-shapes-separated/ConceptMap.element.dependsOn.shex
node shex-partition.js fhir-shapes.shex '<ConceptMap.element.map>' > ./fhir-shapes-separated/ConceptMap.element.map.shex
node shex-partition.js fhir-shapes.shex '<Condition>' > ./fhir-shapes-separated/Condition.shex
node shex-partition.js fhir-shapes.shex '<Condition.category>' > ./fhir-shapes-separated/Condition.category.shex
node shex-partition.js fhir-shapes.shex '<Condition.category.coding>' > ./fhir-shapes-separated/Condition.category.coding.shex
node shex-partition.js fhir-shapes.shex '<Condition.code>' > ./fhir-shapes-separated/Condition.code.shex
node shex-partition.js fhir-shapes.shex '<Condition.code.coding>' > ./fhir-shapes-separated/Condition.code.coding.shex
node shex-partition.js fhir-shapes.shex '<Condition.dueTo>' > ./fhir-shapes-separated/Condition.dueTo.shex
node shex-partition.js fhir-shapes.shex '<Condition.evidence>' > ./fhir-shapes-separated/Condition.evidence.shex
node shex-partition.js fhir-shapes.shex '<Condition.location>' > ./fhir-shapes-separated/Condition.location.shex
node shex-partition.js fhir-shapes.shex '<Condition.occurredFollowing>' > ./fhir-shapes-separated/Condition.occurredFollowing.shex
node shex-partition.js fhir-shapes.shex '<Condition.stage>' > ./fhir-shapes-separated/Condition.stage.shex
node shex-partition.js fhir-shapes.shex '<Conformance>' > ./fhir-shapes-separated/Conformance.shex
node shex-partition.js fhir-shapes.shex '<Conformance.contact>' > ./fhir-shapes-separated/Conformance.contact.shex
node shex-partition.js fhir-shapes.shex '<Conformance.document>' > ./fhir-shapes-separated/Conformance.document.shex
node shex-partition.js fhir-shapes.shex '<Conformance.implementation>' > ./fhir-shapes-separated/Conformance.implementation.shex
node shex-partition.js fhir-shapes.shex '<Conformance.messaging>' > ./fhir-shapes-separated/Conformance.messaging.shex
node shex-partition.js fhir-shapes.shex '<Conformance.messaging.event>' > ./fhir-shapes-separated/Conformance.messaging.event.shex
node shex-partition.js fhir-shapes.shex '<Conformance.rest>' > ./fhir-shapes-separated/Conformance.rest.shex
node shex-partition.js fhir-shapes.shex '<Conformance.rest.interaction>' > ./fhir-shapes-separated/Conformance.rest.interaction.shex
node shex-partition.js fhir-shapes.shex '<Conformance.rest.operation>' > ./fhir-shapes-separated/Conformance.rest.operation.shex
node shex-partition.js fhir-shapes.shex '<Conformance.rest.resource>' > ./fhir-shapes-separated/Conformance.rest.resource.shex
node shex-partition.js fhir-shapes.shex '<Conformance.rest.resource.interaction>' > ./fhir-shapes-separated/Conformance.rest.resource.interaction.shex
node shex-partition.js fhir-shapes.shex '<Conformance.rest.resource.searchParam>' > ./fhir-shapes-separated/Conformance.rest.resource.searchParam.shex
node shex-partition.js fhir-shapes.shex '<Conformance.rest.security>' > ./fhir-shapes-separated/Conformance.rest.security.shex
node shex-partition.js fhir-shapes.shex '<Conformance.rest.security.certificate>' > ./fhir-shapes-separated/Conformance.rest.security.certificate.shex
node shex-partition.js fhir-shapes.shex '<Conformance.software>' > ./fhir-shapes-separated/Conformance.software.shex
node shex-partition.js fhir-shapes.shex '<ContactPoint>' > ./fhir-shapes-separated/ContactPoint.shex
node shex-partition.js fhir-shapes.shex '<Contract>' > ./fhir-shapes-separated/Contract.shex
node shex-partition.js fhir-shapes.shex '<Contract.actor>' > ./fhir-shapes-separated/Contract.actor.shex
node shex-partition.js fhir-shapes.shex '<Contract.friendly>' > ./fhir-shapes-separated/Contract.friendly.shex
node shex-partition.js fhir-shapes.shex '<Contract.legal>' > ./fhir-shapes-separated/Contract.legal.shex
node shex-partition.js fhir-shapes.shex '<Contract.rule>' > ./fhir-shapes-separated/Contract.rule.shex
node shex-partition.js fhir-shapes.shex '<Contract.signer>' > ./fhir-shapes-separated/Contract.signer.shex
node shex-partition.js fhir-shapes.shex '<Contract.term>' > ./fhir-shapes-separated/Contract.term.shex
node shex-partition.js fhir-shapes.shex '<Contract.term.actor>' > ./fhir-shapes-separated/Contract.term.actor.shex
node shex-partition.js fhir-shapes.shex '<Contract.term.valuedItem>' > ./fhir-shapes-separated/Contract.term.valuedItem.shex
node shex-partition.js fhir-shapes.shex '<Contract.valuedItem>' > ./fhir-shapes-separated/Contract.valuedItem.shex
node shex-partition.js fhir-shapes.shex '<Contraindication>' > ./fhir-shapes-separated/Contraindication.shex
node shex-partition.js fhir-shapes.shex '<Contraindication.mitigation>' > ./fhir-shapes-separated/Contraindication.mitigation.shex
node shex-partition.js fhir-shapes.shex '<Coverage>' > ./fhir-shapes-separated/Coverage.shex
node shex-partition.js fhir-shapes.shex '<DataElement>' > ./fhir-shapes-separated/DataElement.shex
node shex-partition.js fhir-shapes.shex '<DataElement.contact>' > ./fhir-shapes-separated/DataElement.contact.shex
node shex-partition.js fhir-shapes.shex '<DataElement.mapping>' > ./fhir-shapes-separated/DataElement.mapping.shex
node shex-partition.js fhir-shapes.shex '<date>' > ./fhir-shapes-separated/date.shex
node shex-partition.js fhir-shapes.shex '<dateTime>' > ./fhir-shapes-separated/dateTime.shex
node shex-partition.js fhir-shapes.shex '<decimal>' > ./fhir-shapes-separated/decimal.shex
node shex-partition.js fhir-shapes.shex '<Device>' > ./fhir-shapes-separated/Device.shex
node shex-partition.js fhir-shapes.shex '<DeviceComponent>' > ./fhir-shapes-separated/DeviceComponent.shex
node shex-partition.js fhir-shapes.shex '<DeviceComponent.productionSpecification>' > ./fhir-shapes-separated/DeviceComponent.productionSpecification.shex
node shex-partition.js fhir-shapes.shex '<DeviceMetric>' > ./fhir-shapes-separated/DeviceMetric.shex
node shex-partition.js fhir-shapes.shex '<DeviceMetric.calibration>' > ./fhir-shapes-separated/DeviceMetric.calibration.shex
node shex-partition.js fhir-shapes.shex '<DeviceUseRequest>' > ./fhir-shapes-separated/DeviceUseRequest.shex
node shex-partition.js fhir-shapes.shex '<DeviceUseStatement>' > ./fhir-shapes-separated/DeviceUseStatement.shex
node shex-partition.js fhir-shapes.shex '<DiagnosticOrder>' > ./fhir-shapes-separated/DiagnosticOrder.shex
node shex-partition.js fhir-shapes.shex '<DiagnosticOrder.event>' > ./fhir-shapes-separated/DiagnosticOrder.event.shex
node shex-partition.js fhir-shapes.shex '<DiagnosticOrder.event.description>' > ./fhir-shapes-separated/DiagnosticOrder.event.description.shex
node shex-partition.js fhir-shapes.shex '<DiagnosticOrder.event.description.coding>' > ./fhir-shapes-separated/DiagnosticOrder.event.description.coding.shex
node shex-partition.js fhir-shapes.shex '<DiagnosticOrder.extension>' > ./fhir-shapes-separated/DiagnosticOrder.extension.shex
node shex-partition.js fhir-shapes.shex '<DiagnosticOrder.identifier>' > ./fhir-shapes-separated/DiagnosticOrder.identifier.shex
node shex-partition.js fhir-shapes.shex '<DiagnosticOrder.item>' > ./fhir-shapes-separated/DiagnosticOrder.item.shex
node shex-partition.js fhir-shapes.shex '<DiagnosticOrder.item.code>' > ./fhir-shapes-separated/DiagnosticOrder.item.code.shex
node shex-partition.js fhir-shapes.shex '<DiagnosticOrder.item.code.coding>' > ./fhir-shapes-separated/DiagnosticOrder.item.code.coding.shex
node shex-partition.js fhir-shapes.shex '<DiagnosticReport>' > ./fhir-shapes-separated/DiagnosticReport.shex
node shex-partition.js fhir-shapes.shex '<DiagnosticReport.image>' > ./fhir-shapes-separated/DiagnosticReport.image.shex
node shex-partition.js fhir-shapes.shex '<DiagnosticReport.name.coding>' > ./fhir-shapes-separated/DiagnosticReport.name.coding.shex
node shex-partition.js fhir-shapes.shex '<DocumentManifest>' > ./fhir-shapes-separated/DocumentManifest.shex
node shex-partition.js fhir-shapes.shex '<DocumentManifest.content>' > ./fhir-shapes-separated/DocumentManifest.content.shex
node shex-partition.js fhir-shapes.shex '<DocumentManifest.related>' > ./fhir-shapes-separated/DocumentManifest.related.shex
node shex-partition.js fhir-shapes.shex '<DocumentReference>' > ./fhir-shapes-separated/DocumentReference.shex
node shex-partition.js fhir-shapes.shex '<DocumentReference.content>' > ./fhir-shapes-separated/DocumentReference.content.shex
node shex-partition.js fhir-shapes.shex '<DocumentReference.context>' > ./fhir-shapes-separated/DocumentReference.context.shex
node shex-partition.js fhir-shapes.shex '<DocumentReference.context.related>' > ./fhir-shapes-separated/DocumentReference.context.related.shex
node shex-partition.js fhir-shapes.shex '<DocumentReference.relatesTo>' > ./fhir-shapes-separated/DocumentReference.relatesTo.shex
node shex-partition.js fhir-shapes.shex '<DomainResource>' > ./fhir-shapes-separated/DomainResource.shex
node shex-partition.js fhir-shapes.shex '<Element>' > ./fhir-shapes-separated/Element.shex
node shex-partition.js fhir-shapes.shex '<ElementDefinition>' > ./fhir-shapes-separated/ElementDefinition.shex
node shex-partition.js fhir-shapes.shex '<ElementDefinition.binding>' > ./fhir-shapes-separated/ElementDefinition.binding.shex
node shex-partition.js fhir-shapes.shex '<ElementDefinition.constraint>' > ./fhir-shapes-separated/ElementDefinition.constraint.shex
node shex-partition.js fhir-shapes.shex '<ElementDefinition.mapping>' > ./fhir-shapes-separated/ElementDefinition.mapping.shex
node shex-partition.js fhir-shapes.shex '<ElementDefinition.slicing>' > ./fhir-shapes-separated/ElementDefinition.slicing.shex
node shex-partition.js fhir-shapes.shex '<ElementDefinition.type>' > ./fhir-shapes-separated/ElementDefinition.type.shex
node shex-partition.js fhir-shapes.shex '<EligibilityRequest>' > ./fhir-shapes-separated/EligibilityRequest.shex
node shex-partition.js fhir-shapes.shex '<EligibilityResponse>' > ./fhir-shapes-separated/EligibilityResponse.shex
node shex-partition.js fhir-shapes.shex '<Encounter>' > ./fhir-shapes-separated/Encounter.shex
node shex-partition.js fhir-shapes.shex '<Encounter.hospitalization>' > ./fhir-shapes-separated/Encounter.hospitalization.shex
node shex-partition.js fhir-shapes.shex '<Encounter.location>' > ./fhir-shapes-separated/Encounter.location.shex
node shex-partition.js fhir-shapes.shex '<Encounter.participant>' > ./fhir-shapes-separated/Encounter.participant.shex
node shex-partition.js fhir-shapes.shex '<Encounter.statusHistory>' > ./fhir-shapes-separated/Encounter.statusHistory.shex
node shex-partition.js fhir-shapes.shex '<EnrollmentRequest>' > ./fhir-shapes-separated/EnrollmentRequest.shex
node shex-partition.js fhir-shapes.shex '<EnrollmentResponse>' > ./fhir-shapes-separated/EnrollmentResponse.shex
node shex-partition.js fhir-shapes.shex '<EpisodeOfCare>' > ./fhir-shapes-separated/EpisodeOfCare.shex
node shex-partition.js fhir-shapes.shex '<EpisodeOfCare.careTeam>' > ./fhir-shapes-separated/EpisodeOfCare.careTeam.shex
node shex-partition.js fhir-shapes.shex '<EpisodeOfCare.statusHistory>' > ./fhir-shapes-separated/EpisodeOfCare.statusHistory.shex
node shex-partition.js fhir-shapes.shex '<ExplanationOfBenefit>' > ./fhir-shapes-separated/ExplanationOfBenefit.shex
node shex-partition.js fhir-shapes.shex '<Extension>' > ./fhir-shapes-separated/Extension.shex
node shex-partition.js fhir-shapes.shex '<FamilyMemberHistory>' > ./fhir-shapes-separated/FamilyMemberHistory.shex
node shex-partition.js fhir-shapes.shex '<FamilyMemberHistory.condition>' > ./fhir-shapes-separated/FamilyMemberHistory.condition.shex
node shex-partition.js fhir-shapes.shex '<Flag>' > ./fhir-shapes-separated/Flag.shex
node shex-partition.js fhir-shapes.shex '<Goal>' > ./fhir-shapes-separated/Goal.shex
node shex-partition.js fhir-shapes.shex '<Goal.outcome>' > ./fhir-shapes-separated/Goal.outcome.shex
node shex-partition.js fhir-shapes.shex '<Group>' > ./fhir-shapes-separated/Group.shex
node shex-partition.js fhir-shapes.shex '<Group.characteristic>' > ./fhir-shapes-separated/Group.characteristic.shex
node shex-partition.js fhir-shapes.shex '<HealthcareService>' > ./fhir-shapes-separated/HealthcareService.shex
node shex-partition.js fhir-shapes.shex '<HealthcareService.availableTime>' > ./fhir-shapes-separated/HealthcareService.availableTime.shex
node shex-partition.js fhir-shapes.shex '<HealthcareService.notAvailable>' > ./fhir-shapes-separated/HealthcareService.notAvailable.shex
node shex-partition.js fhir-shapes.shex '<HealthcareService.serviceType>' > ./fhir-shapes-separated/HealthcareService.serviceType.shex
node shex-partition.js fhir-shapes.shex '<HumanName>' > ./fhir-shapes-separated/HumanName.shex
node shex-partition.js fhir-shapes.shex '<id>' > ./fhir-shapes-separated/id.shex
node shex-partition.js fhir-shapes.shex '<Identifier>' > ./fhir-shapes-separated/Identifier.shex
node shex-partition.js fhir-shapes.shex '<ImagingObjectSelection>' > ./fhir-shapes-separated/ImagingObjectSelection.shex
node shex-partition.js fhir-shapes.shex '<ImagingObjectSelection.study>' > ./fhir-shapes-separated/ImagingObjectSelection.study.shex
node shex-partition.js fhir-shapes.shex '<ImagingObjectSelection.study.series>' > ./fhir-shapes-separated/ImagingObjectSelection.study.series.shex
node shex-partition.js fhir-shapes.shex '<ImagingObjectSelection.study.series.instance>' > ./fhir-shapes-separated/ImagingObjectSelection.study.series.instance.shex
node shex-partition.js fhir-shapes.shex '<ImagingObjectSelection.study.series.instance.frames>' > ./fhir-shapes-separated/ImagingObjectSelection.study.series.instance.frames.shex
node shex-partition.js fhir-shapes.shex '<ImagingStudy>' > ./fhir-shapes-separated/ImagingStudy.shex
node shex-partition.js fhir-shapes.shex '<ImagingStudy.series>' > ./fhir-shapes-separated/ImagingStudy.series.shex
node shex-partition.js fhir-shapes.shex '<ImagingStudy.series.instance>' > ./fhir-shapes-separated/ImagingStudy.series.instance.shex
node shex-partition.js fhir-shapes.shex '<Immunization>' > ./fhir-shapes-separated/Immunization.shex
node shex-partition.js fhir-shapes.shex '<Immunization.explanation>' > ./fhir-shapes-separated/Immunization.explanation.shex
node shex-partition.js fhir-shapes.shex '<Immunization.reaction>' > ./fhir-shapes-separated/Immunization.reaction.shex
node shex-partition.js fhir-shapes.shex '<ImmunizationRecommendation>' > ./fhir-shapes-separated/ImmunizationRecommendation.shex
node shex-partition.js fhir-shapes.shex '<ImmunizationRecommendation.recommendation>' > ./fhir-shapes-separated/ImmunizationRecommendation.recommendation.shex
node shex-partition.js fhir-shapes.shex '<ImmunizationRecommendation.recommendation.dateCriterion>' > ./fhir-shapes-separated/ImmunizationRecommendation.recommendation.dateCriterion.shex
node shex-partition.js fhir-shapes.shex '<ImmunizationRecommendation.recommendation.protocol>' > ./fhir-shapes-separated/ImmunizationRecommendation.recommendation.protocol.shex
node shex-partition.js fhir-shapes.shex '<Immunization.vaccinationProtocol>' > ./fhir-shapes-separated/Immunization.vaccinationProtocol.shex
node shex-partition.js fhir-shapes.shex '<instant>' > ./fhir-shapes-separated/instant.shex
node shex-partition.js fhir-shapes.shex '<integer>' > ./fhir-shapes-separated/integer.shex
node shex-partition.js fhir-shapes.shex '<List>' > ./fhir-shapes-separated/List.shex
node shex-partition.js fhir-shapes.shex '<List.entry>' > ./fhir-shapes-separated/List.entry.shex
node shex-partition.js fhir-shapes.shex '<Location>' > ./fhir-shapes-separated/Location.shex
node shex-partition.js fhir-shapes.shex '<Location.address>' > ./fhir-shapes-separated/Location.address.shex
node shex-partition.js fhir-shapes.shex '<Location.position>' > ./fhir-shapes-separated/Location.position.shex
node shex-partition.js fhir-shapes.shex '<Media>' > ./fhir-shapes-separated/Media.shex
node shex-partition.js fhir-shapes.shex '<Medication>' > ./fhir-shapes-separated/Medication.shex
node shex-partition.js fhir-shapes.shex '<MedicationAdministration>' > ./fhir-shapes-separated/MedicationAdministration.shex
node shex-partition.js fhir-shapes.shex '<MedicationAdministration.dosage>' > ./fhir-shapes-separated/MedicationAdministration.dosage.shex
node shex-partition.js fhir-shapes.shex '<MedicationDispense>' > ./fhir-shapes-separated/MedicationDispense.shex
node shex-partition.js fhir-shapes.shex '<MedicationDispense.dosageInstruction>' > ./fhir-shapes-separated/MedicationDispense.dosageInstruction.shex
node shex-partition.js fhir-shapes.shex '<MedicationDispense.substitution>' > ./fhir-shapes-separated/MedicationDispense.substitution.shex
node shex-partition.js fhir-shapes.shex '<Medication.package>' > ./fhir-shapes-separated/Medication.package.shex
node shex-partition.js fhir-shapes.shex '<Medication.package.content>' > ./fhir-shapes-separated/Medication.package.content.shex
node shex-partition.js fhir-shapes.shex '<MedicationPrescription>' > ./fhir-shapes-separated/MedicationPrescription.shex
node shex-partition.js fhir-shapes.shex '<MedicationPrescription.dispense>' > ./fhir-shapes-separated/MedicationPrescription.dispense.shex
node shex-partition.js fhir-shapes.shex '<MedicationPrescription.dosageInstruction>' > ./fhir-shapes-separated/MedicationPrescription.dosageInstruction.shex
node shex-partition.js fhir-shapes.shex '<MedicationPrescription.substitution>' > ./fhir-shapes-separated/MedicationPrescription.substitution.shex
node shex-partition.js fhir-shapes.shex '<Medication.product>' > ./fhir-shapes-separated/Medication.product.shex
node shex-partition.js fhir-shapes.shex '<Medication.product.batch>' > ./fhir-shapes-separated/Medication.product.batch.shex
node shex-partition.js fhir-shapes.shex '<Medication.product.ingredient>' > ./fhir-shapes-separated/Medication.product.ingredient.shex
node shex-partition.js fhir-shapes.shex '<MedicationStatement>' > ./fhir-shapes-separated/MedicationStatement.shex
node shex-partition.js fhir-shapes.shex '<MedicationStatement.dosage>' > ./fhir-shapes-separated/MedicationStatement.dosage.shex
node shex-partition.js fhir-shapes.shex '<MessageHeader>' > ./fhir-shapes-separated/MessageHeader.shex
node shex-partition.js fhir-shapes.shex '<MessageHeader.destination>' > ./fhir-shapes-separated/MessageHeader.destination.shex
node shex-partition.js fhir-shapes.shex '<MessageHeader.response>' > ./fhir-shapes-separated/MessageHeader.response.shex
node shex-partition.js fhir-shapes.shex '<MessageHeader.source>' > ./fhir-shapes-separated/MessageHeader.source.shex
node shex-partition.js fhir-shapes.shex '<Meta>' > ./fhir-shapes-separated/Meta.shex
node shex-partition.js fhir-shapes.shex '<NamingSystem>' > ./fhir-shapes-separated/NamingSystem.shex
node shex-partition.js fhir-shapes.shex '<NamingSystem.contact>' > ./fhir-shapes-separated/NamingSystem.contact.shex
node shex-partition.js fhir-shapes.shex '<NamingSystem.uniqueId>' > ./fhir-shapes-separated/NamingSystem.uniqueId.shex
node shex-partition.js fhir-shapes.shex '<Narrative>' > ./fhir-shapes-separated/Narrative.shex
node shex-partition.js fhir-shapes.shex '<NutritionOrder>' > ./fhir-shapes-separated/NutritionOrder.shex
node shex-partition.js fhir-shapes.shex '<NutritionOrder.enteralFormula>' > ./fhir-shapes-separated/NutritionOrder.enteralFormula.shex
node shex-partition.js fhir-shapes.shex '<NutritionOrder.oralDiet>' > ./fhir-shapes-separated/NutritionOrder.oralDiet.shex
node shex-partition.js fhir-shapes.shex '<NutritionOrder.oralDiet.nutrient>' > ./fhir-shapes-separated/NutritionOrder.oralDiet.nutrient.shex
node shex-partition.js fhir-shapes.shex '<NutritionOrder.oralDiet.texture>' > ./fhir-shapes-separated/NutritionOrder.oralDiet.texture.shex
node shex-partition.js fhir-shapes.shex '<NutritionOrder.supplement>' > ./fhir-shapes-separated/NutritionOrder.supplement.shex
node shex-partition.js fhir-shapes.shex '<Observation>' > ./fhir-shapes-separated/Observation.shex
node shex-partition.js fhir-shapes.shex '<Observation.code.coding>' > ./fhir-shapes-separated/Observation.code.coding.shex
node shex-partition.js fhir-shapes.shex '<Observation.interpretation.coding>' > ./fhir-shapes-separated/Observation.interpretation.coding.shex
node shex-partition.js fhir-shapes.shex '<Observation.referenceRange>' > ./fhir-shapes-separated/Observation.referenceRange.shex
node shex-partition.js fhir-shapes.shex '<Observation.referenceRange.age.high>' > ./fhir-shapes-separated/Observation.referenceRange.age.high.shex
node shex-partition.js fhir-shapes.shex '<Observation.referenceRange.age.low>' > ./fhir-shapes-separated/Observation.referenceRange.age.low.shex
node shex-partition.js fhir-shapes.shex '<Observation.related>' > ./fhir-shapes-separated/Observation.related.shex
node shex-partition.js fhir-shapes.shex '<oid>' > ./fhir-shapes-separated/oid.shex
node shex-partition.js fhir-shapes.shex '<OperationDefinition>' > ./fhir-shapes-separated/OperationDefinition.shex
node shex-partition.js fhir-shapes.shex '<OperationDefinition.contact>' > ./fhir-shapes-separated/OperationDefinition.contact.shex
node shex-partition.js fhir-shapes.shex '<OperationDefinition.parameter>' > ./fhir-shapes-separated/OperationDefinition.parameter.shex
node shex-partition.js fhir-shapes.shex '<OperationDefinition.parameter.part>' > ./fhir-shapes-separated/OperationDefinition.parameter.part.shex
node shex-partition.js fhir-shapes.shex '<OperationOutcome>' > ./fhir-shapes-separated/OperationOutcome.shex
node shex-partition.js fhir-shapes.shex '<OperationOutcome.issue>' > ./fhir-shapes-separated/OperationOutcome.issue.shex
node shex-partition.js fhir-shapes.shex '<Order>' > ./fhir-shapes-separated/Order.shex
node shex-partition.js fhir-shapes.shex '<OrderResponse>' > ./fhir-shapes-separated/OrderResponse.shex
node shex-partition.js fhir-shapes.shex '<Order.when>' > ./fhir-shapes-separated/Order.when.shex
node shex-partition.js fhir-shapes.shex '<Organization>' > ./fhir-shapes-separated/Organization.shex
node shex-partition.js fhir-shapes.shex '<Organization.contact>' > ./fhir-shapes-separated/Organization.contact.shex
node shex-partition.js fhir-shapes.shex '<Parameters>' > ./fhir-shapes-separated/Parameters.shex
node shex-partition.js fhir-shapes.shex '<Parameters.parameter>' > ./fhir-shapes-separated/Parameters.parameter.shex
node shex-partition.js fhir-shapes.shex '<Parameters.parameter.part>' > ./fhir-shapes-separated/Parameters.parameter.part.shex
node shex-partition.js fhir-shapes.shex '<Patient>' > ./fhir-shapes-separated/Patient.shex
node shex-partition.js fhir-shapes.shex '<Patient.address>' > ./fhir-shapes-separated/Patient.address.shex
node shex-partition.js fhir-shapes.shex '<Patient.animal>' > ./fhir-shapes-separated/Patient.animal.shex
node shex-partition.js fhir-shapes.shex '<Patient.birthDate>' > ./fhir-shapes-separated/Patient.birthDate.shex
node shex-partition.js fhir-shapes.shex '<Patient.communication>' > ./fhir-shapes-separated/Patient.communication.shex
node shex-partition.js fhir-shapes.shex '<Patient.contact>' > ./fhir-shapes-separated/Patient.contact.shex
node shex-partition.js fhir-shapes.shex '<Patient.contact.relationship.coding>' > ./fhir-shapes-separated/Patient.contact.relationship.coding.shex
node shex-partition.js fhir-shapes.shex '<Patient.link>' > ./fhir-shapes-separated/Patient.link.shex
node shex-partition.js fhir-shapes.shex '<Patient.telecom>' > ./fhir-shapes-separated/Patient.telecom.shex
node shex-partition.js fhir-shapes.shex '<PaymentNotice>' > ./fhir-shapes-separated/PaymentNotice.shex
node shex-partition.js fhir-shapes.shex '<PaymentReconciliation>' > ./fhir-shapes-separated/PaymentReconciliation.shex
node shex-partition.js fhir-shapes.shex '<PaymentReconciliation.detail>' > ./fhir-shapes-separated/PaymentReconciliation.detail.shex
node shex-partition.js fhir-shapes.shex '<PaymentReconciliation.note>' > ./fhir-shapes-separated/PaymentReconciliation.note.shex
node shex-partition.js fhir-shapes.shex '<Period>' > ./fhir-shapes-separated/Period.shex
node shex-partition.js fhir-shapes.shex '<Person>' > ./fhir-shapes-separated/Person.shex
node shex-partition.js fhir-shapes.shex '<Person.link>' > ./fhir-shapes-separated/Person.link.shex
node shex-partition.js fhir-shapes.shex '<positiveInt>' > ./fhir-shapes-separated/positiveInt.shex
node shex-partition.js fhir-shapes.shex '<Practitioner>' > ./fhir-shapes-separated/Practitioner.shex
node shex-partition.js fhir-shapes.shex '<Practitioner.address>' > ./fhir-shapes-separated/Practitioner.address.shex
node shex-partition.js fhir-shapes.shex '<Practitioner.identifier>' > ./fhir-shapes-separated/Practitioner.identifier.shex
node shex-partition.js fhir-shapes.shex '<Practitioner.name>' > ./fhir-shapes-separated/Practitioner.name.shex
node shex-partition.js fhir-shapes.shex '<Practitioner.practitionerRole>' > ./fhir-shapes-separated/Practitioner.practitionerRole.shex
node shex-partition.js fhir-shapes.shex '<Practitioner.qualification>' > ./fhir-shapes-separated/Practitioner.qualification.shex
node shex-partition.js fhir-shapes.shex '<Practitioner.telecom>' > ./fhir-shapes-separated/Practitioner.telecom.shex
node shex-partition.js fhir-shapes.shex '<Procedure>' > ./fhir-shapes-separated/Procedure.shex
node shex-partition.js fhir-shapes.shex '<Procedure.bodySite>' > ./fhir-shapes-separated/Procedure.bodySite.shex
node shex-partition.js fhir-shapes.shex '<Procedure.device>' > ./fhir-shapes-separated/Procedure.device.shex
node shex-partition.js fhir-shapes.shex '<Procedure.performer>' > ./fhir-shapes-separated/Procedure.performer.shex
node shex-partition.js fhir-shapes.shex '<Procedure.relatedItem>' > ./fhir-shapes-separated/Procedure.relatedItem.shex
node shex-partition.js fhir-shapes.shex '<ProcedureRequest>' > ./fhir-shapes-separated/ProcedureRequest.shex
node shex-partition.js fhir-shapes.shex '<ProcedureRequest.bodySite>' > ./fhir-shapes-separated/ProcedureRequest.bodySite.shex
node shex-partition.js fhir-shapes.shex '<ProcessRequest>' > ./fhir-shapes-separated/ProcessRequest.shex
node shex-partition.js fhir-shapes.shex '<ProcessRequest.item>' > ./fhir-shapes-separated/ProcessRequest.item.shex
node shex-partition.js fhir-shapes.shex '<ProcessResponse>' > ./fhir-shapes-separated/ProcessResponse.shex
node shex-partition.js fhir-shapes.shex '<ProcessResponse.notes>' > ./fhir-shapes-separated/ProcessResponse.notes.shex
node shex-partition.js fhir-shapes.shex '<Provenance>' > ./fhir-shapes-separated/Provenance.shex
node shex-partition.js fhir-shapes.shex '<Provenance.agent>' > ./fhir-shapes-separated/Provenance.agent.shex
node shex-partition.js fhir-shapes.shex '<Provenance.entity>' > ./fhir-shapes-separated/Provenance.entity.shex
node shex-partition.js fhir-shapes.shex '<Quantity>' > ./fhir-shapes-separated/Quantity.shex
node shex-partition.js fhir-shapes.shex '<Questionnaire>' > ./fhir-shapes-separated/Questionnaire.shex
node shex-partition.js fhir-shapes.shex '<QuestionnaireAnswers>' > ./fhir-shapes-separated/QuestionnaireAnswers.shex
node shex-partition.js fhir-shapes.shex '<QuestionnaireAnswers.group>' > ./fhir-shapes-separated/QuestionnaireAnswers.group.shex
node shex-partition.js fhir-shapes.shex '<QuestionnaireAnswers.group.question>' > ./fhir-shapes-separated/QuestionnaireAnswers.group.question.shex
node shex-partition.js fhir-shapes.shex '<QuestionnaireAnswers.group.question.answer>' > ./fhir-shapes-separated/QuestionnaireAnswers.group.question.answer.shex
node shex-partition.js fhir-shapes.shex '<Questionnaire.group>' > ./fhir-shapes-separated/Questionnaire.group.shex
node shex-partition.js fhir-shapes.shex '<Questionnaire.group.extension>' > ./fhir-shapes-separated/Questionnaire.group.extension.shex
node shex-partition.js fhir-shapes.shex '<Questionnaire.group.question>' > ./fhir-shapes-separated/Questionnaire.group.question.shex
node shex-partition.js fhir-shapes.shex '<Questionnaire.group.question.extension>' > ./fhir-shapes-separated/Questionnaire.group.question.extension.shex
node shex-partition.js fhir-shapes.shex '<Questionnaire.group.title>' > ./fhir-shapes-separated/Questionnaire.group.title.shex
node shex-partition.js fhir-shapes.shex '<Range>' > ./fhir-shapes-separated/Range.shex
node shex-partition.js fhir-shapes.shex '<Ratio>' > ./fhir-shapes-separated/Ratio.shex
node shex-partition.js fhir-shapes.shex '<Reference>' > ./fhir-shapes-separated/Reference.shex
node shex-partition.js fhir-shapes.shex '<ReferralRequest>' > ./fhir-shapes-separated/ReferralRequest.shex
node shex-partition.js fhir-shapes.shex '<RelatedPerson>' > ./fhir-shapes-separated/RelatedPerson.shex
node shex-partition.js fhir-shapes.shex '<Resource>' > ./fhir-shapes-separated/Resource.shex
node shex-partition.js fhir-shapes.shex '<RiskAssessment>' > ./fhir-shapes-separated/RiskAssessment.shex
node shex-partition.js fhir-shapes.shex '<RiskAssessment.prediction>' > ./fhir-shapes-separated/RiskAssessment.prediction.shex
node shex-partition.js fhir-shapes.shex '<SampledData>' > ./fhir-shapes-separated/SampledData.shex
node shex-partition.js fhir-shapes.shex '<Schedule>' > ./fhir-shapes-separated/Schedule.shex
node shex-partition.js fhir-shapes.shex '<SearchParameter>' > ./fhir-shapes-separated/SearchParameter.shex
node shex-partition.js fhir-shapes.shex '<SearchParameter.contact>' > ./fhir-shapes-separated/SearchParameter.contact.shex
node shex-partition.js fhir-shapes.shex '<Signature>' > ./fhir-shapes-separated/Signature.shex
node shex-partition.js fhir-shapes.shex '<Slot>' > ./fhir-shapes-separated/Slot.shex
node shex-partition.js fhir-shapes.shex '<Specimen>' > ./fhir-shapes-separated/Specimen.shex
node shex-partition.js fhir-shapes.shex '<Specimen.collection>' > ./fhir-shapes-separated/Specimen.collection.shex
node shex-partition.js fhir-shapes.shex '<Specimen.collection.bodySiteCodeableConcept>' > ./fhir-shapes-separated/Specimen.collection.bodySiteCodeableConcept.shex
node shex-partition.js fhir-shapes.shex '<Specimen.collection.bodySiteCodeableConcept.coding>' > ./fhir-shapes-separated/Specimen.collection.bodySiteCodeableConcept.coding.shex
node shex-partition.js fhir-shapes.shex '<Specimen.collection.quantity>' > ./fhir-shapes-separated/Specimen.collection.quantity.shex
node shex-partition.js fhir-shapes.shex '<Specimen.container>' > ./fhir-shapes-separated/Specimen.container.shex
node shex-partition.js fhir-shapes.shex '<Specimen.treatment>' > ./fhir-shapes-separated/Specimen.treatment.shex
node shex-partition.js fhir-shapes.shex '<Specimen.type.coding>' > ./fhir-shapes-separated/Specimen.type.coding.shex
node shex-partition.js fhir-shapes.shex '<string>' > ./fhir-shapes-separated/string.shex
node shex-partition.js fhir-shapes.shex '<StructureDefinition>' > ./fhir-shapes-separated/StructureDefinition.shex
node shex-partition.js fhir-shapes.shex '<StructureDefinition.contact>' > ./fhir-shapes-separated/StructureDefinition.contact.shex
node shex-partition.js fhir-shapes.shex '<StructureDefinition.differential>' > ./fhir-shapes-separated/StructureDefinition.differential.shex
node shex-partition.js fhir-shapes.shex '<StructureDefinition.mapping>' > ./fhir-shapes-separated/StructureDefinition.mapping.shex
node shex-partition.js fhir-shapes.shex '<StructureDefinition.snapshot>' > ./fhir-shapes-separated/StructureDefinition.snapshot.shex
node shex-partition.js fhir-shapes.shex '<Subscription>' > ./fhir-shapes-separated/Subscription.shex
node shex-partition.js fhir-shapes.shex '<Subscription.channel>' > ./fhir-shapes-separated/Subscription.channel.shex
node shex-partition.js fhir-shapes.shex '<Substance>' > ./fhir-shapes-separated/Substance.shex
node shex-partition.js fhir-shapes.shex '<Substance.ingredient>' > ./fhir-shapes-separated/Substance.ingredient.shex
node shex-partition.js fhir-shapes.shex '<Substance.instance>' > ./fhir-shapes-separated/Substance.instance.shex
node shex-partition.js fhir-shapes.shex '<Supply>' > ./fhir-shapes-separated/Supply.shex
node shex-partition.js fhir-shapes.shex '<Supply.dispense>' > ./fhir-shapes-separated/Supply.dispense.shex
node shex-partition.js fhir-shapes.shex '<time>' > ./fhir-shapes-separated/time.shex
node shex-partition.js fhir-shapes.shex '<Timing>' > ./fhir-shapes-separated/Timing.shex
node shex-partition.js fhir-shapes.shex '<Timing.repeat>' > ./fhir-shapes-separated/Timing.repeat.shex
node shex-partition.js fhir-shapes.shex '<unsignedInt>' > ./fhir-shapes-separated/unsignedInt.shex
node shex-partition.js fhir-shapes.shex '<uri>' > ./fhir-shapes-separated/uri.shex
node shex-partition.js fhir-shapes.shex '<uuid>' > ./fhir-shapes-separated/uuid.shex
node shex-partition.js fhir-shapes.shex '<ValueSet>' > ./fhir-shapes-separated/ValueSet.shex
node shex-partition.js fhir-shapes.shex '<ValueSet.compose>' > ./fhir-shapes-separated/ValueSet.compose.shex
node shex-partition.js fhir-shapes.shex '<ValueSet.compose.include>' > ./fhir-shapes-separated/ValueSet.compose.include.shex
node shex-partition.js fhir-shapes.shex '<ValueSet.compose.include.concept>' > ./fhir-shapes-separated/ValueSet.compose.include.concept.shex
node shex-partition.js fhir-shapes.shex '<ValueSet.compose.include.filter>' > ./fhir-shapes-separated/ValueSet.compose.include.filter.shex
node shex-partition.js fhir-shapes.shex '<ValueSet.contact>' > ./fhir-shapes-separated/ValueSet.contact.shex
node shex-partition.js fhir-shapes.shex '<ValueSet.define>' > ./fhir-shapes-separated/ValueSet.define.shex
node shex-partition.js fhir-shapes.shex '<ValueSet.define.concept>' > ./fhir-shapes-separated/ValueSet.define.concept.shex
node shex-partition.js fhir-shapes.shex '<ValueSet.define.concept.designation>' > ./fhir-shapes-separated/ValueSet.define.concept.designation.shex
node shex-partition.js fhir-shapes.shex '<ValueSet.define.concept.display>' > ./fhir-shapes-separated/ValueSet.define.concept.display.shex
node shex-partition.js fhir-shapes.shex '<ValueSet.expansion>' > ./fhir-shapes-separated/ValueSet.expansion.shex
node shex-partition.js fhir-shapes.shex '<ValueSet.expansion.contains>' > ./fhir-shapes-separated/ValueSet.expansion.contains.shex
node shex-partition.js fhir-shapes.shex '<ValueSet.expansion.contains.display>' > ./fhir-shapes-separated/ValueSet.expansion.contains.display.shex
node shex-partition.js fhir-shapes.shex '<ValueSet.expansion.parameter>' > ./fhir-shapes-separated/ValueSet.expansion.parameter.shex
node shex-partition.js fhir-shapes.shex '<VisionPrescription>' > ./fhir-shapes-separated/VisionPrescription.shex
node shex-partition.js fhir-shapes.shex '<VisionPrescription.dispense>' > ./fhir-shapes-separated/VisionPrescription.dispense.shex
